### ISSUE TITLE
Build does not start - meta-browser/firefox is a blacklisted recipe

### ISSUE THREAD

**Issue by hemanth-krishna** [engmda-cpe/manifests#2]
<a href="https://github.com/hemanth-krishna"><img src="https://avatars.githubusercontent.com/u/13857634?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hemanth-krishna](https://github.com/hemanth-krishna)**
_Wednesday Jun 29, 2016 at 17:42 GMT_
_Originally opened as https://github.com/sanandin/manifests/issues/2_

----

`
11:29 $ MACHINE=raspberrypi2 bitbake rpi-ui-image
WARNING: Host distribution "Ubuntu-16.04" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
Loading cache: 100% |####################################################################################################################################################################################| ETA:  00:00:00
Loaded 2 entries from dependency cache.
Parsing recipes: 100% |##################################################################################################################################################################################| ETA:  00:00:00
Parsing of 1701 .bb files complete (1 cached, 1700 parsed). 2226 targets, 142 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'firefox' (but /home/hkrishna/devel/yocto/actvideo_rpi2/rpi2_browser_repo/rpi2_browser/meta-ui/recipes-ui-image/rpi-ui-image/rpi-ui-image.bb RDEPENDS on or otherwise requires it)
ERROR: firefox was skipped: Recipe is blacklisted: BROKEN: fails to build with gcc-6
NOTE: Runtime target 'firefox' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['firefox']
ERROR: Required build target 'rpi-ui-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['rpi-ui-image', 'firefox']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
`

**Comment by hemanth-krishna** [comment]
<a href="https://github.com/manbirsingh01"><img src="https://avatars.githubusercontent.com/u/19944595?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [manbirsingh01](https://github.com/manbirsingh01)**
_Thursday Jun 30, 2016 at 09:32 GMT_

----

@hemanth-krishna, I faced the same issue, when I tried to build it.

Command :-  MACHINE=raspberrypi2 bitbake rpi-ui-image 

ERROR: Required build target 'rpi-ui-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['rpi-ui-image', 'firefox']

After that I gave command to build firefox alone to get its status and got following error message

Command:-  MACHINE=raspberrypi2 bitbake firefox
ERROR: Nothing PROVIDES 'firefox'
ERROR: firefox was skipped: Recipe is blacklisted: BROKEN: fails to build with gcc-6.

According to error message, because of gcc version, firefox recipe is skipped and it give error message "Missing or unbuildable dependency chain was: ['rpi-ui-image', 'firefox']".

To verify error, I checked default gcc version for krogoth branch and  it's 5.3. So, It's not because of gcc version. 

To get more details,  I checked firefox recipe. In recipe, variable **# PNBLACKLIST[firefox] ?= "BROKEN: fails to build with gcc-6"** is used without any validation of gcc version.

**# According to yocto manual:-** 
PNBLACKLIST :-  Lists recipes you do not want the OpenEmbedded build system to build. This variable works in conjunction with the blacklist class, which the recipe must inherit globally.To prevent a recipe from being built, inherit the class globally and use the variable in your local.conf file. Here is an example that prevents myrecipe from being built:
     INHERIT += "blacklist"
     PNBLACKLIST[myrecipe] = "Not supported by our organization."
                    
This is the root cause for the issue.

**Comment by hemanth-krishna** [comment]
<a href="https://github.com/manbirsingh01"><img src="https://avatars.githubusercontent.com/u/19944595?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [manbirsingh01](https://github.com/manbirsingh01)**
_Thursday Jun 30, 2016 at 09:58 GMT_

----

 **Possible solutions:-**

1. Comment following line in firefox recipe -  meta-browser/recipes-mozilla/firefox/firefox_38.7.1esr.bb as we are not working with gcc-6

     PNBLACKLIST[firefox] ?= "BROKEN: fails to build with gcc-6"                                                                    

2. We can use stable version - jethro other than master as master is keep upgrading. Last time when we built rpi-ui-image, master was on commit - 825ea93 and in next commit - e61fc92,  they blacklisted browser with message "firefox, cef3, chromium: blacklist, fails to build with gcc-6". Now we are pointing to latest master.

Build has started fine with both solutions.

**Comment by hemanth-krishna** [comment]
https://github.com/engmda-cpe/manifests/commit/ae214e73e105f5f1a0012740cb3856ccd2b36ee9 commit addressed in manifests by moving firefox to Jethro

**Comment by hemanth-krishna** [comment]
See http://lists.openembedded.org/pipermail/openembedded-devel/2016-June/107860.html - suggests fix in local.conf

```shell
#Stop the blacklist due to broken gcc6 
PNBLACKLIST[firefox] = ""
```

**Comment by hemanth-krishna** [comment]
Changes needed in manifest (rpi_browser.xml) and in local.conf

**Comment by hemanth-krishna** [comment]
[meta-ui](https://github.com/engmda-cpe/meta-ui/commit/d9a3af02e9895a3ead5590f1bf3b60e04f2862c5) and [manifests](https://github.com/engmda-cpe/manifests/commit/82a7c73c6757ce16bc9b75714b06de083cf3dcb1) commits should solve this.

**Comment by manbirsingh01** [comment]
@hemanth-krishna  rpi-ui-image is built successfully with above changes. Also verified with flashing it on raspberrypi2.

**Comment by hemanth-krishna** [comment]
Marked close - appears to be working fine now.
